name: CI
on: [push]
jobs:
  build:
    name: Build Boilerplate
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
      - run: yarn test
