name: CI
on: [push]
jobs:
  build:
    name: Build Boilerplate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-site
          path: dist
  publish:
    name: Publish site to Netlify
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-site
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
